### ISSUE TITLE
prfc has an inaccurate description on 3-way handshake

### ISSUE THREAD

**Issue by heaventourist** [CrimsonVista/NetworkSecuritySpring2019#18]
The 3-way handshake in the prfc is not accurate. Please refer to the discussion on campuswire.

**Comment by lol-fi** [comment]
Lines 281-314 are copy pasted from campus wire and merged during class. So I'm unsure what difference you are referring to.

**Comment by sethnielson** [comment]
@lol-fi the problem is that somebody swapped the "syn,ack" part. It should be in line 2, but it's in line 3. If you look on Campuswire, you'll see a discussion about this.

https://campuswire.com/c/G800DF8C8/feed/156
