### ISSUE TITLE
Escape Room Auto Grader - Checking for Valid Code

### ISSUE THREAD

**Issue by chelseadeane14** [CrimsonVista/NetworkSecuritySpring2019#2]
Line 289  `self.assertTrue(digitInts[i] < digitInts[i+1], "{} not correct format.".format(digits)) ` does not work when two of the digits are the same. So, even though 3,7,8,8 is valid, this line will return invalid.

**Comment by sethnielson** [comment]
The original intention was that duplicate numbers would not be repeated. This has been clarified in the specification and the auto-grader is correct.

Closing
