### ISSUE TITLE
some typo in the playground quickstart

### ISSUE THREAD

**Issue by MrMegaMango** [CrimsonVista/NetworkSecuritySpring2019#9]
1. pip install wheel (not pip wheel)

2. git clone https://github.com/CrimsonVista/BitPoints-Bank-Playground3
 (not  https://github.com/BitPoints-Bank-Playground3)

**Comment by MrMegaMango** [comment]
Bank Client [Admin]> transfer account1 100 "This is an example memo."
Client gives me "Unknown command transfer"

**Comment by sethnielson** [comment]
Fixed "account transfer" and "pip install wheel". could not find the github that is mislabeled or else I already fixed it
